
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class ChallengeRewardSettingReader
{
    private readonly System.Collections.Generic.Dictionary<string, ChallengeRewardSetting> _dataMap;
    private readonly System.Collections.Generic.List<ChallengeRewardSetting> _dataList;
    
    public ChallengeRewardSettingReader(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, ChallengeRewardSetting>();
        _dataList = new System.Collections.Generic.List<ChallengeRewardSetting>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ChallengeRewardSetting _v;
            _v = ChallengeRewardSetting.DeserializeChallengeRewardSetting(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ChallengeRewardSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<ChallengeRewardSetting> DataList => _dataList;

    public ChallengeRewardSetting GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ChallengeRewardSetting Get(string key) => _dataMap[key];
    public ChallengeRewardSetting this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

