
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ChallengeRewardSetting : Luban.BeanBase
{
    public ChallengeRewardSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        ChallengeId = _buf.ReadString();
        Floor = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ClearReward = new System.Collections.Generic.List<XiaoCao.Item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { XiaoCao.Item _e0;  _e0 = ExternalTypeUtil.ToItem(Item.DeserializeItem(_buf)); ClearReward.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);FirstReward = new System.Collections.Generic.List<XiaoCao.Item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { XiaoCao.Item _e0;  _e0 = ExternalTypeUtil.ToItem(Item.DeserializeItem(_buf)); FirstReward.Add(_e0);}}
        Comment = _buf.ReadString();
    }

    public static ChallengeRewardSetting DeserializeChallengeRewardSetting(ByteBuf _buf)
    {
        return new ChallengeRewardSetting(_buf);
    }

    /// <summary>
    /// 奖励配置id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 挑战关卡id
    /// </summary>
    public readonly string ChallengeId;
    /// <summary>
    /// 通过层数
    /// </summary>
    public readonly int Floor;
    /// <summary>
    /// 重复通关奖励
    /// </summary>
    public readonly System.Collections.Generic.List<XiaoCao.Item> ClearReward;
    /// <summary>
    /// 首通特殊奖励
    /// </summary>
    public readonly System.Collections.Generic.List<XiaoCao.Item> FirstReward;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = 1972669598;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "challengeId:" + ChallengeId + ","
        + "floor:" + Floor + ","
        + "clearReward:" + Luban.StringUtil.CollectionToString(ClearReward) + ","
        + "firstReward:" + Luban.StringUtil.CollectionToString(FirstReward) + ","
        + "comment:" + Comment + ","
        + "}";
    }
}

}
