
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class ChapterSettingReader
{
    private readonly System.Collections.Generic.Dictionary<int, ChapterSetting> _dataMap;
    private readonly System.Collections.Generic.List<ChapterSetting> _dataList;
    
    public ChapterSettingReader(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ChapterSetting>();
        _dataList = new System.Collections.Generic.List<ChapterSetting>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ChapterSetting _v;
            _v = ChapterSetting.DeserializeChapterSetting(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ChapterSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<ChapterSetting> DataList => _dataList;

    public ChapterSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ChapterSetting Get(int key) => _dataMap[key];
    public ChapterSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

