
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ChapterSetting : Luban.BeanBase
{
    public ChapterSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Levels = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Levels.Add(_e0);}}
    }

    public static ChapterSetting DeserializeChapterSetting(ByteBuf _buf)
    {
        return new ChapterSetting(_buf);
    }

    /// <summary>
    /// 章节
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<int> Levels;
   
    public const int __ID__ = 1556673891;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levels:" + Luban.StringUtil.CollectionToString(Levels) + ","
        + "}";
    }
}

}
