
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial struct CreateEnemyInfo
{
    public CreateEnemyInfo(ByteBuf _buf) 
    {
        Enemys = _buf.ReadString();
        Count = _buf.ReadInt();
    }

    public static CreateEnemyInfo DeserializeCreateEnemyInfo(ByteBuf _buf)
    {
        return new CreateEnemyInfo(_buf);
    }

    public readonly string Enemys;
    public readonly int Count;
   

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "enemys:" + Enemys + ","
        + "count:" + Count + ","
        + "}";
    }
}

}
