
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CreateEnemyGroups : Luban.BeanBase
{
    public CreateEnemyGroups(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EnemyInfos = new System.Collections.Generic.List<CreateEnemyInfo>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { CreateEnemyInfo _e0;  _e0 = CreateEnemyInfo.DeserializeCreateEnemyInfo(_buf); EnemyInfos.Add(_e0);}}
        ForceFollow = _buf.ReadInt();
    }

    public static CreateEnemyGroups DeserializeCreateEnemyGroups(ByteBuf _buf)
    {
        return new CreateEnemyGroups(_buf);
    }

    /// <summary>
    /// 关卡/组/分支,
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 敌人id, 数量
    /// </summary>
    public readonly System.Collections.Generic.List<CreateEnemyInfo> EnemyInfos;
    /// <summary>
    /// 强制跟随(0,无视 1跟随,-1不跟随)
    /// </summary>
    public readonly int ForceFollow;
   
    public const int __ID__ = 134275264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "enemyInfos:" + Luban.StringUtil.CollectionToString(EnemyInfos) + ","
        + "forceFollow:" + ForceFollow + ","
        + "}";
    }
}

}
