
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class CreateEnemyGroupsReader
{
    private readonly System.Collections.Generic.Dictionary<string, CreateEnemyGroups> _dataMap;
    private readonly System.Collections.Generic.List<CreateEnemyGroups> _dataList;
    
    public CreateEnemyGroupsReader(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, CreateEnemyGroups>();
        _dataList = new System.Collections.Generic.List<CreateEnemyGroups>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CreateEnemyGroups _v;
            _v = CreateEnemyGroups.DeserializeCreateEnemyGroups(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CreateEnemyGroups> DataMap => _dataMap;
    public System.Collections.Generic.List<CreateEnemyGroups> DataList => _dataList;

    public CreateEnemyGroups GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CreateEnemyGroups Get(string key) => _dataMap[key];
    public CreateEnemyGroups this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

