
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial struct Item
{
    public Item(ByteBuf _buf) 
    {
        Type = (XiaoCao.ItemType)_buf.ReadInt();
        Name = _buf.ReadString();
        Count = _buf.ReadInt();
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new Item(_buf);
    }

    public readonly XiaoCao.ItemType Type;
    public readonly string Name;
    public readonly int Count;
   

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "name:" + Name + ","
        + "count:" + Count + ","
        + "}";
    }
}

}
