
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class LevelSetting : Luban.BeanBase
{
    public LevelSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Title = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EnemyLvList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EnemyLvList.Add(_e0);}}
        ImgName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Reward = new System.Collections.Generic.List<XiaoCao.Item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { XiaoCao.Item _e0;  _e0 = ExternalTypeUtil.ToItem(Item.DeserializeItem(_buf)); Reward.Add(_e0);}}
        RoleId = _buf.ReadInt();
    }

    public static LevelSetting DeserializeLevelSetting(ByteBuf _buf)
    {
        return new LevelSetting(_buf);
    }

    /// <summary>
    /// 关卡序号(数字)
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    public readonly System.Collections.Generic.List<int> EnemyLvList;
    /// <summary>
    /// 图片id
    /// </summary>
    public readonly string ImgName;
    /// <summary>
    /// 奖励:HolyRelic,&quot;name&quot;,1|HolyRelic,&quot;name&quot;,1
    /// </summary>
    public readonly System.Collections.Generic.List<XiaoCao.Item> Reward;
    /// <summary>
    /// #default=-1
    /// </summary>
    public readonly int RoleId;
   
    public const int __ID__ = -865590708;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "enemyLvList:" + Luban.StringUtil.CollectionToString(EnemyLvList) + ","
        + "imgName:" + ImgName + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "roleId:" + RoleId + ","
        + "}";
    }
}

}
