
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class LevelSetting : Luban.BeanBase
{
    public LevelSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Title = _buf.ReadString();
        ImgName = _buf.ReadString();
        Reward = ExternalTypeUtil.ToItem(Item.DeserializeItem(_buf));
    }

    public static LevelSetting DeserializeLevelSetting(ByteBuf _buf)
    {
        return new LevelSetting(_buf);
    }

    /// <summary>
    /// 关卡序号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 图片id
    /// </summary>
    public readonly string ImgName;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly XiaoCao.Item Reward;
   
    public const int __ID__ = -865590708;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "imgName:" + ImgName + ","
        + "reward:" + Reward + ","
        + "}";
    }
}

}
