
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillUpgradeSetting : Luban.BeanBase
{
    public SkillUpgradeSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NeedLv = _buf.ReadInt();
        Cd = _buf.ReadFloat();
        LevelDamageFactor = _buf.ReadFloat();
        MaxLevel = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Cost = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Cost.Add(_e0);}}
    }

    public static SkillUpgradeSetting DeserializeSkillUpgradeSetting(ByteBuf _buf)
    {
        return new SkillUpgradeSetting(_buf);
    }

    public readonly string Id;
    public readonly int NeedLv;
    public readonly float Cd;
    public readonly float LevelDamageFactor;
    public readonly int MaxLevel;
    public readonly System.Collections.Generic.List<int> Cost;
   
    public const int __ID__ = 222507301;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "needLv:" + NeedLv + ","
        + "cd:" + Cd + ","
        + "levelDamageFactor:" + LevelDamageFactor + ","
        + "maxLevel:" + MaxLevel + ","
        + "cost:" + Luban.StringUtil.CollectionToString(Cost) + ","
        + "}";
    }
}

}
