
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Skill
{ 
    public enum EActType
    {
        /// <summary>
        /// 常规技能
        /// </summary>
        Skill = 1,
        /// <summary>
        /// 普攻
        /// </summary>
        NorAtk = 2,
        /// <summary>
        /// 翻滚跳跃等
        /// </summary>
        Other = 3,
    }

} 

