
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillUpgradeSetting : Luban.BeanBase
{
    public SkillUpgradeSetting(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NeedItems = new System.Collections.Generic.List<XiaoCao.Item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { XiaoCao.Item _e0;  _e0 = ExternalTypeUtil.ToItem(Item.DeserializeItem(_buf)); NeedItems.Add(_e0);}}
    }

    public static SkillUpgradeSetting DeserializeSkillUpgradeSetting(ByteBuf _buf)
    {
        return new SkillUpgradeSetting(_buf);
    }

    /// <summary>
    /// 技能序号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级所需
    /// </summary>
    public readonly System.Collections.Generic.List<XiaoCao.Item> NeedItems;
   
    public const int __ID__ = 222507301;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "needItems:" + Luban.StringUtil.CollectionToString(NeedItems) + ","
        + "}";
    }
}

}
