
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public SkillSettingReader SkillSettingReader {get; }
    public LevelSettingReader LevelSettingReader {get; }
    public ChapterSettingReader ChapterSettingReader {get; }
    public CreateEnemyGroupsReader CreateEnemyGroupsReader {get; }
    public SkillUpgradeSettingReader SkillUpgradeSettingReader {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SkillSettingReader = new SkillSettingReader(loader("skillsettingreader"));
        LevelSettingReader = new LevelSettingReader(loader("levelsettingreader"));
        ChapterSettingReader = new ChapterSettingReader(loader("chaptersettingreader"));
        CreateEnemyGroupsReader = new CreateEnemyGroupsReader(loader("createenemygroupsreader"));
        SkillUpgradeSettingReader = new SkillUpgradeSettingReader(loader("skillupgradesettingreader"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        SkillSettingReader.ResolveRef(this);
        LevelSettingReader.ResolveRef(this);
        ChapterSettingReader.ResolveRef(this);
        CreateEnemyGroupsReader.ResolveRef(this);
        SkillUpgradeSettingReader.ResolveRef(this);
    }
}

}
