//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// Gen By "XiaoCaoEditor.LayerTagGenerator"
public sealed class Layers
{
    
    public const int BODY_PHYSICS = 10;
    
    public const int BODY_PHYSICS_MASK = 1024;
    
    public const int DEFAULT = 0;
    
    public const int DEFAULT_MASK = 1;
    
    public const int ENEMY = 7;
    
    public const int ENEMY_MASK = 128;
    
    public const int ENEMY_ATK = 9;
    
    public const int ENEMY_ATK_MASK = 512;
    
    public const int GROUND = 3;
    
    public const int GROUND_MASK = 8;
    
    public const int IGNORE_RAYCAST = 2;
    
    public const int IGNORE_RAYCAST_MASK = 4;
    
    public const int PLAYER = 6;
    
    public const int PLAYER_MASK = 64;
    
    public const int PLAYER_ATK = 8;
    
    public const int PLAYER_ATK_MASK = 256;
    
    public const int TRANSPARENT_FX = 1;
    
    public const int TRANSPARENT_FX_MASK = 2;
    
    public const int UI = 5;
    
    public const int UI_MASK = 32;
    
    public const int WALL = 12;
    
    public const int WALL_MASK = 4096;
    
    public const int WALL_BLOCK = 13;
    
    public const int WALL_BLOCK_MASK = 8192;
    
    public const int WATER = 4;
    
    public const int WATER_MASK = 16;
    
    public const int WITHOUT_BODY = 11;
    
    public const int WITHOUT_BODY_MASK = 2048;
}
