//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// Gen By "XiaoCaoEditor.LayerTagGenerator"
public sealed class Tags
{
    
    public const string EDITOR_ONLY = "EditorOnly";
    
    public const string ENEMY = "Enemy";
    
    public const string FINISH = "Finish";
    
    public const string GAME_CONTROLLER = "GameController";
    
    public const string MAIN_CAMERA = "MainCamera";
    
    public const string PLAYER = "Player";
    
    public const string PLAYER_ATTACK = "PlayerAttack";
    
    public const string RESPAWN = "Respawn";
    
    public const string UNTAGGED = "Untagged";
}
